#!/usr/bin/env node
// Anthropic <-> OpenAI proxy for Claude Code.
//
// AUTO-GENERATED by scripts/build.js — do not edit by hand.
// Source lives in src/. Run `npm run build` to regenerate.
//
// Usage:
//   node proxy.js --base https://api.openai.com/v1 --key sk-xxx --port 8082
//   or via env: OPENAI_BASE_URL, OPENAI_API_KEY, PORT, MODEL_OVERRIDE
//
// Then in Claude Code:
//   export ANTHROPIC_BASE_URL=http://localhost:8082
//   export ANTHROPIC_AUTH_TOKEN=any
//   claude --bare                  # interactive
//   claude -p --bare "your prompt" # non-interactive
//
// Notes:
//   * Thinking blocks from Claude Code are dropped (no OpenAI analogue).
//     Disable extended thinking in Claude Code if you want clean runs.
//   * Streaming is translated chunk-by-chunk from OpenAI SSE to Anthropic SSE.
//   * Tool calls: streams are stitched via OpenAI's `index` field, so multi-tool
//     and partial-arg deltas work.

'use strict';

const __ccproxy_externalRequire = require;
const __ccproxy_modules = {};
const __ccproxy_load = (name) => {
  const m = __ccproxy_modules[name];
  if (m.loaded) return m.exports;
  m.loaded = true;
  m.factory.call(void 0, m._require, m.exports, m);
  return m.exports;
};

function __ccproxy_register(name, factory) {
  const m = { exports: {}, loaded: false, factory };
  // Require shim: './foo.js' -> __ccproxy_load('foo'); anything else falls
  // through to the captured outer require (handles 'http' and other built-ins).
  m._require = (id) => {
    if (typeof id === 'string' && id.startsWith('./')) {
      return __ccproxy_load(id.replace(/^\.\//, '').replace(/\.js$/, ''));
    }
    return __ccproxy_externalRequire(id);
  };
  __ccproxy_modules[name] = m;
}

__ccproxy_register("catalog", (require, exports, module) => {
// ---------- models.dev catalog: cache + lookup ----------
//
// Pulls the full models.dev model catalog (https://models.dev/api.json,
// ~3.2MB, 167 providers) once, caches it on disk, and serves O(1) lookups
// for context window, max output, vision support, and reasoning field shape.
//
// Boot behavior:
//   * First-ever boot (no cache file): blocks until the fetch finishes.
//   * Subsequent boots: returns instantly from disk, kicks off a background
//     refresh that updates the in-memory copy when it finishes.
//   * If the background fetch fails: log a one-liner, keep serving from
//     the cached copy. Never crash.
//
// All consumers should call findModel(bareId) — never read .data directly.

const fs = require('node:fs');
const path = require('node:path');
const process = require('node:process');

const CATALOG_URL = 'https://models.dev/api.json';
const CACHE_DIR = path.join(process.cwd(), '.cache');
const CACHE_FILE = path.join(CACHE_DIR, 'models.dev.json');
const CACHE_TTL_MS = 24 * 60 * 60 * 1000; // 24h

// Vendored copy of models.dev's api.json, shipped inside the package. This is
// the seed: a fresh clone (or `npm install -g cc-proxy`) has data available at
// first boot with no network round-trip. The background refresh in
// loadCatalog() still updates the in-memory copy and the on-disk .cache file
// when it can, so the bundled copy is never more stale than the release date.
//
// We probe a few candidate paths because the module can live in two layouts:
//   * unbundled (tests, src/ running directly): the JSON sits next to us in
//     src/catalog-data.json — `__dirname + 'catalog-data.json'`.
//   * bundled (npm/published, bin/cc-proxy.js -> lib/proxy.js): the JSON is
//     shipped at src/catalog-data.json one level up from lib/.
//   * manual curl-install (lib/proxy.js only): no JSON is available — we
//     return null and the network fetch path in loadCatalog() takes over.
let _bundledCatalogCache;

// In-memory pointer. Swapped atomically when a background refresh succeeds.
let currentCatalog = null;

function readBundledCatalog() {
  if (_bundledCatalogCache !== undefined) return _bundledCatalogCache;
  const candidates = [
    path.join(__dirname, 'catalog-data.json'),
    path.join(__dirname, '..', 'src', 'catalog-data.json'),
  ];
  for (const p of candidates) {
    try {
      const raw = fs.readFileSync(p, 'utf8');
      const j = JSON.parse(raw);
      if (j && typeof j === 'object' && j.providers) {
        _bundledCatalogCache = j;
        return j;
      }
    } catch {
      // missing or corrupt at this path — try the next candidate
    }
  }
  _bundledCatalogCache = null;
  return null;
}

function log(line) {
  process.stdout.write(`[catalog] ${line}\n`);
}

function ensureCacheDir() {
  try {
    fs.mkdirSync(CACHE_DIR, { recursive: true });
  } catch {
    // .cache dir creation failed (read-only fs?); fall through — we'll just
    // not be able to persist, but the in-memory load still works for this run.
  }
}

function readCacheFile() {
  try {
    const raw = fs.readFileSync(CACHE_FILE, 'utf8');
    const j = JSON.parse(raw);
    if (j && typeof j === 'object' && j.providers) return j;
  } catch {
    // missing or invalid; treat as no cache
  }
  return null;
}

function writeCacheFile(data) {
  ensureCacheDir();
  const tmp = CACHE_FILE + '.tmp';
  try {
    fs.writeFileSync(tmp, JSON.stringify(data));
    fs.renameSync(tmp, CACHE_FILE);
  } catch {
    // best-effort; not fatal
  }
}

async function fetchFresh() {
  const r = await fetch(CATALOG_URL);
  if (!r.ok) throw new Error(`HTTP ${r.status}`);
  const j = await r.json();
  // Sanity: the file is a flat { "<provider>": { ... } } object; wrap it.
  if (!j || typeof j !== 'object') throw new Error('malformed catalog');
  const providers = {};
  let modelCount = 0;
  for (const [pname, p] of Object.entries(j)) {
    if (!p || typeof p !== 'object' || !p.models) continue;
    providers[pname] = p;
    modelCount += Object.keys(p.models).length;
  }
  return {
    providers,
    _meta: { fetchedAt: Date.now(), providers: Object.keys(providers).length, models: modelCount },
  };
}

function applyInPlace(data) {
  // Atomic pointer swap: consumers calling getCatalog() always see a
  // fully-populated object, never a partial update.
  currentCatalog = data;
}

function getCatalog() {
  return currentCatalog;
}

// Module-init: seed the in-memory catalog from the vendored bundled copy so
// lookups work even before the async loadCatalog() at boot has run, and on
// fresh installs with no .cache file. The background refresh path overrides
// this pointer when it succeeds. readBundledCatalog() returns null if the
// bundled file is absent (e.g. running from raw src/ without the JSON) — in
// which case the catalog stays empty until loadCatalog() runs.
(function seedFromBundle() {
  if (currentCatalog) return;
  const bundled = readBundledCatalog();
  if (bundled) applyInPlace(bundled);
})();

// loadCatalog(): await once at boot.
//   * If we have a valid cache file (any age), use it and return immediately.
//   * Kick off a background refresh that updates the in-memory copy.
//   * First-ever boot (no cache file) blocks until the foreground fetch
//     finishes, so the proxy never serves a request with an empty catalog.
async function loadCatalog({ forceRefresh = false } = {}) {
  if (forceRefresh) {
    try {
      const data = await fetchFresh();
      applyInPlace(data);
      writeCacheFile(data);
      log(
        `refreshed from models.dev (${data._meta.providers} providers, ${data._meta.models} models)`,
      );
    } catch (e) {
      if (!currentCatalog) {
        // No cached copy and refresh failed: rethrow so the caller knows.
        throw new Error(`models.dev fetch failed and no cache available: ${e.message}`);
      }
      log(`refresh failed: ${e.message}`);
    }
    return currentCatalog;
  }

  const cached = readCacheFile();
  if (cached) {
    applyInPlace(cached);
    // Background refresh regardless — keeps the cache fresh for next boot.
    // We don't await this; the caller proceeds.
    setImmediate(() => backgroundRefresh());
    return currentCatalog;
  }

  // No cache file: first-ever boot. Block on the fetch.
  log('no cache found, downloading models.dev (one-time, ~3MB)...');
  try {
    const data = await fetchFresh();
    applyInPlace(data);
    writeCacheFile(data);
    log(`loaded from models.dev (${data._meta.providers} providers, ${data._meta.models} models)`);
  } catch (e) {
    throw new Error(`models.dev fetch failed and no cache available: ${e.message}`);
  }
  return currentCatalog;
}

async function backgroundRefresh() {
  try {
    const data = await fetchFresh();
    applyInPlace(data);
    writeCacheFile(data);
    log(`updated from models.dev (${data._meta.providers} providers, ${data._meta.models} models)`);
  } catch (e) {
    log(`background refresh failed: ${e.message}`);
  }
}

// Strip a trailing '-[Provider]', '-provider', or '/[Provider]' suffix so
// the lookup finds the same model regardless of which provider the client
// is routing through. Examples:
//   'deepseek-v4-flash-free-[opencode]' -> 'deepseek-v4-flash-free'
//   'openai/gpt-4o'                     -> 'openai/gpt-4o'  (provider-prefix form kept)
//   'gpt-4o'                            -> 'gpt-4o'
function stripProviderSuffix(model) {
  if (!model) return model;
  // '[Provider]' suffix first (most common from Claude Code routing)
  let m = model.replace(/-\[[^\]]+\]\s*$/, '');
  // bare '-provider' suffix is ambiguous (could be a real model name), so
  // only strip when the suffix matches a known provider name in the catalog.
  // We do this lazily: findModel() will fall through to the suffix-stripped
  // form if the original id isn't found, so we don't pre-strip here.
  return m;
}

// findModel(bareId, catalog?) — returns the model entry, or null.
//   1. exact id match in any provider's models
//   2. provider-prefix form: 'openai/gpt-4o' looks up provider='openai', id='gpt-4o'
//   3. case-insensitive id match
//   4. last resort: strip the '-<word>' suffix and try again (handles
//      'claude-3-5-sonnet-20241022' → 'claude-3-5-sonnet')
// Canonical provider names — when an entry is from one of these, we prefer
// it over a mirror entry that may have stale/incorrect fields.
const CANONICAL_PROVIDERS = new Set([
  'openai',
  'anthropic',
  'google',
  'xai',
  'meta',
  'mistral',
  'deepseek',
  'cohere',
  'groq',
  'openrouter',
  'azure',
  'bedrock',
  'vertex',
]);

function _entryScore(entry, providerName) {
  if (!entry) return 0;
  let n = 0;
  if (entry.family) n++;
  if (entry.limit && entry.limit.context) n++;
  if (entry.limit && entry.limit.output) n++;
  if (Array.isArray(entry.reasoning_options) && entry.reasoning_options.length) n += 2;
  if (entry.modalities && Array.isArray(entry.modalities.input)) n++;
  if (typeof entry.reasoning === 'boolean') n++;
  // Big bonus for being from a canonical provider — this trumps field count
  // when a mirror provider has more populated but wrong fields.
  if (providerName && CANONICAL_PROVIDERS.has(providerName)) n += 100;
  return n;
}

// findModelEntry(bareId, catalog?) — resolves a model id and returns
//   { entry, providerName } where providerName is the catalog provider the
//   winning entry was sourced from. Returns null if not found.
//
// `providerName` is the catalog metadata provider, NOT necessarily the
// upstream the request is routed through — `moonshotai/kimi-k2.6` resolves
// here to the `moonshotai` catalog provider (and `nvidia/nemotron-30b` to
// `openrouter`, via the canonical score bonus). NIM-specific request shaping
// is gated on the model's `-[Provider]` suffix (see src/nim.js isNimModel),
// which is why this value is exported only for diagnostics, not as the gate.
function findModelEntry(bareId, catalog) {
  if (!bareId) return null;
  const data = catalog || currentCatalog;
  if (!data || !data.providers) return null;
  return _findIn(bareId, data, new Set());
}

function findModel(bareId, catalog) {
  const r = findModelEntry(bareId, catalog);
  return r ? r.entry : null;
}

function _findIn(id, data, visited) {
  if (visited.has(id)) return null;
  visited.add(id);

  // 2. provider/id form
  const slash = id.indexOf('/');
  if (slash > 0) {
    const pname = id.slice(0, slash);
    const mid = id.slice(slash + 1);
    const p = data.providers[pname];
    if (p && p.models && p.models[mid]) return { entry: p.models[mid], providerName: pname };
  }

  // 1. exact id — when multiple providers have the same id, prefer canonical
  //    providers (openai/anthropic/google/etc.). These carry the most
  //    authoritative metadata; mirror providers sometimes have stale fields.
  let bestExact = null;
  let bestExactScore = -1;
  let bestExactProvider = null;
  for (const pname of Object.keys(data.providers)) {
    const p = data.providers[pname];
    if (!p.models || !p.models[id]) continue;
    const entry = p.models[id];
    const score = _entryScore(entry, pname);
    if (score > bestExactScore) {
      bestExact = entry;
      bestExactScore = score;
      bestExactProvider = pname;
    }
  }
  if (bestExact) return { entry: bestExact, providerName: bestExactProvider };

  // 3. case-insensitive — same canonical-preference logic
  const lower = id.toLowerCase();
  let bestCI = null;
  let bestCIScore = -1;
  let bestCIProvider = null;
  for (const pname of Object.keys(data.providers)) {
    const p = data.providers[pname];
    if (!p.models) continue;
    for (const [mid, entry] of Object.entries(p.models)) {
      if (mid.toLowerCase() !== lower) continue;
      const s = _entryScore(entry, pname);
      if (s > bestCIScore) {
        bestCI = entry;
        bestCIScore = s;
        bestCIProvider = pname;
      }
    }
  }
  if (bestCI) return { entry: bestCI, providerName: bestCIProvider };

  // 4. suffix strip: progressively remove trailing '-<word>' segments.
  //    Stops at the first match, when no more dashes remain, or when we
  //    loop back to an id we've already tried.
  let cur = stripProviderSuffix(id);
  while (cur !== id) {
    const r = _findIn(cur, data, visited);
    if (r) return r;
    const shorter = cur.replace(/-[^-]+$/, '');
    if (!shorter || !shorter.includes('-')) break;
    cur = shorter;
  }
  return null;
}

// Convenience: does this model accept image input?
function modelSupportsVision(model) {
  const entry = findModel(model);
  if (!entry || !entry.modalities) return false;
  return Array.isArray(entry.modalities.input) && entry.modalities.input.includes('image');
}

// loadCatalogSync() — synchronous load from disk only. No network. Returns
// the cached catalog if available; otherwise the vendored bundled copy;
// otherwise null. Used by tests so they don't need a before() hook, and as a
// last-resort sync source. The integration test / production path uses
// the async loadCatalog() which handles the network fetch.
function loadCatalogSync() {
  const cached = readCacheFile();
  if (cached) {
    applyInPlace(cached);
    return cached;
  }
  const bundled = readBundledCatalog();
  if (bundled) {
    applyInPlace(bundled);
    return bundled;
  }
  return null;
}

module.exports = {
  loadCatalog,
  loadCatalogSync,
  getCatalog,
  findModel,
  findModelEntry,
  stripProviderSuffix,
  modelSupportsVision,
  CACHE_FILE,
  CACHE_TTL_MS,
};
});

__ccproxy_register("ids", (require, exports, module) => {
// ---------- id + sse helpers ----------

function msgId() {
  return 'msg_' + Math.random().toString(36).slice(2, 26);
}

function reqId() {
  return 'req_' + Math.random().toString(36).slice(2, 18);
}

function sse(eventType, data) {
  return `event: ${eventType}\ndata: ${JSON.stringify(data)}\n\n`;
}

module.exports = { msgId, reqId, sse };
});

__ccproxy_register("errors", (require, exports, module) => {
const { reqId } = require('./ids.js');

function anthropicError(status, message) {
  let type = 'api_error';
  if (status === 400) type = 'invalid_request_error';
  else if (status === 401) type = 'authentication_error';
  else if (status === 403) type = 'permission_error';
  else if (status === 404) type = 'not_found_error';
  else if (status === 429) type = 'rate_limit_error';
  else if (status === 503 || status === 529) type = 'overloaded_error';
  return { type: 'error', error: { type, message } };
}

function writeJsonError(res, status, message) {
  res.writeHead(status, { 'content-type': 'application/json' });
  res.end(JSON.stringify(anthropicError(status, message)));
}

module.exports = { anthropicError, writeJsonError, reqId };
});

__ccproxy_register("retry", (require, exports, module) => {
// ---------- fetch with retry ----------
//
// Chat-completions POSTs are safe to retry on 429/5xx and transient network
// errors because the upstream either never received the call or rejected it
// before any state change. We retry only BEFORE the first byte is sent to
// the client — once we start streaming, mid-stream retry would duplicate the
// message_start event and Anthropic SSE has no rewind.
//
// Reference: CLASP/internal/proxy/handler.go:961 doRequestWithRetry. We
// diverge by including 429 (CLASP misses it) and 529 (CLASP excludes it),
// and we honor Retry-After.

const process = require('node:process');

const RETRY_BASE_MS = 250;
const RETRY_MAX_MS = 4000;
// Overridable via env so tests can shorten the deadline; 30s in prod.
const RETRY_TOTAL_DEADLINE_MS =
  Number.isFinite(+process.env.CCPROXY_RETRY_DEADLINE_MS) &&
  +process.env.CCPROXY_RETRY_DEADLINE_MS > 0
    ? +process.env.CCPROXY_RETRY_DEADLINE_MS
    : 30000;
const RETRYABLE_STATUS = new Set([429, 502, 503, 504, 529]);
const RETRYABLE_NET_CODES = new Set([
  'ECONNRESET',
  'ETIMEDOUT',
  'ECONNREFUSED',
  'EAI_AGAIN',
  'UND_ERR_SOCKET',
  'UND_ERR_CONNECT_TIMEOUT',
]);

function sleep(ms, signal) {
  return new Promise((resolve, reject) => {
    if (signal?.aborted) return reject(new Error('aborted'));
    const t = setTimeout(() => {
      cleanup();
      resolve();
    }, ms);
    const onAbort = () => {
      cleanup();
      reject(new Error('aborted'));
    };
    const cleanup = () => {
      clearTimeout(t);
      signal?.removeEventListener('abort', onAbort);
    };
    signal?.addEventListener('abort', onAbort, { once: true });
  });
}

function parseRetryAfter(header) {
  if (!header) return null;
  const s = Number(header);
  if (Number.isFinite(s) && s >= 0) return Math.min(s * 1000, RETRY_MAX_MS);
  const t = Date.parse(header);
  if (!Number.isNaN(t)) return Math.min(Math.max(t - Date.now(), 0), RETRY_MAX_MS);
  return null;
}

function isRetryableNetworkError(e) {
  if (e?.name === 'AbortError') return false;
  const code = e?.cause?.code;
  if (code && RETRYABLE_NET_CODES.has(code)) return true;
  if (typeof e?.message === 'string' && e.message.includes('fetch failed')) return true;
  return false;
}

async function fetchWithRetry(url, opts, signal) {
  const start = Date.now();
  let attempt = 0;
  while (true) {
    if (signal?.aborted) throw new Error('aborted');
    let r;
    try {
      r = await fetch(url, { ...opts, signal });
    } catch (e) {
      if (!isRetryableNetworkError(e) || Date.now() - start >= RETRY_TOTAL_DEADLINE_MS) throw e;
      const delay = Math.min(RETRY_BASE_MS * 2 ** attempt + Math.random() * 100, RETRY_MAX_MS);
      if (process.env.LOG)
        console.log(
          `  ↻ retry ${attempt + 1} after ${Math.round(delay)}ms (network: ${e.cause?.code || e.message})`,
        );
      await sleep(delay, signal);
      attempt++;
      continue;
    }
    if (r.ok) return r;
    if (!RETRYABLE_STATUS.has(r.status) || Date.now() - start >= RETRY_TOTAL_DEADLINE_MS) return r;
    // Drain so the connection can be reused for the next attempt.
    try {
      await r.text();
    } catch {}
    const retryAfter = parseRetryAfter(r.headers.get('retry-after'));
    const delay =
      retryAfter ?? Math.min(RETRY_BASE_MS * 2 ** attempt + Math.random() * 100, RETRY_MAX_MS);
    if (process.env.LOG)
      console.log(`  ↻ retry ${attempt + 1} after ${Math.round(delay)}ms (status ${r.status})`);
    await sleep(delay, signal);
    attempt++;
  }
}

// Returns an AbortSignal that fires when the client disconnects mid-request.
// AbortController is global on Node 18+ — no feature check needed.
function reqAbortSignal(req) {
  if (!req) return undefined;
  const ac = new AbortController();
  req.on('close', () => ac.abort());
  return ac.signal;
}

module.exports = {
  RETRY_BASE_MS,
  RETRY_MAX_MS,
  RETRY_TOTAL_DEADLINE_MS,
  RETRYABLE_STATUS,
  RETRYABLE_NET_CODES,
  sleep,
  parseRetryAfter,
  isRetryableNetworkError,
  fetchWithRetry,
  reqAbortSignal,
};
});

__ccproxy_register("schema", (require, exports, module) => {
// Clean an Anthropic JSON Schema so it's safe to send to the OpenAI Chat
// Completions endpoint. Two things go wrong otherwise:
//   1. OpenAI rejects `format: "uri"` and the schema-level `strict: true`.
//   2. Anthropic (and Claude Code) mark every parameter as required, which
//      causes OpenAI to reject the call when the model omits an optional
//      argument. We re-derive `required` to only the params that are truly
//      required: present in the original `required`, no default, not nullable,
//      not a boolean (flags are almost always optional), and the description
//      doesn't contain "optional"-style phrases.
function cleanupSchemaForChatCompletions(schema) {
  if (!schema || typeof schema !== 'object') return schema;
  const out = JSON.parse(JSON.stringify(schema));
  const visit = (node) => {
    if (!node || typeof node !== 'object') return;
    if (node.format === 'uri') delete node.format;
    delete node.strict;
    if (node.properties && typeof node.properties === 'object') {
      const originalRequired = new Set(Array.isArray(node.required) ? node.required : []);
      const truly = [];
      for (const [name, prop] of Object.entries(node.properties)) {
        if (!originalRequired.has(name)) continue;
        if (typeof prop !== 'object' || !prop) continue;
        if ('default' in prop) continue;
        if (prop.nullable === true) continue;
        if (prop.type === 'boolean') continue;
        const desc = (prop.description || '').toLowerCase();
        if (
          desc.includes('optional') ||
          desc.includes('(optional)') ||
          desc.includes('if not specified') ||
          desc.includes('defaults to') ||
          desc.includes('set to true to') ||
          desc.includes('set to false to') ||
          desc.includes('if provided') ||
          desc.includes('when provided') ||
          desc.includes('can be omitted') ||
          desc.includes('not required') ||
          desc.includes('only provide if')
        )
          continue;
        truly.push(name);
      }
      if (truly.length) node.required = truly;
      else delete node.required;
      for (const v of Object.values(node.properties)) visit(v);
    }
    if (node.items && typeof node.items === 'object') visit(node.items);
  };
  visit(out);
  return out;
}

module.exports = { cleanupSchemaForChatCompletions };
});

__ccproxy_register("models", (require, exports, module) => {
// ---------- model metadata (sourced from models.dev at boot) ----------
//
// All numbers come from the models.dev catalog via src/catalog.js. Hardcoded
// tables lived here before; they're now derived lookups. When the catalog
// is unavailable or a model isn't in it, we fall back to safe defaults.

const { findModel, stripProviderSuffix } = require('./catalog.js');

const ANTHROPIC_CONTEXT = 200000;
// Safe over-report for an unknown model: assumes a small context so the
// usage numbers it returns don't lie about headroom. (32k matches what the
// old hardcoded DEFAULT_CONTEXT_LIMIT used.)
const SAFE_FALLBACK_CONTEXT = 32000;
const SAFE_FALLBACK_OUTPUT = 16384;

function getModelContextLimit(model) {
  if (!model) return SAFE_FALLBACK_CONTEXT;
  const entry = findModel(stripProviderSuffix(model));
  if (entry && entry.limit && typeof entry.limit.context === 'number') {
    return entry.limit.context;
  }
  return SAFE_FALLBACK_CONTEXT;
}

function contextScale(model) {
  return ANTHROPIC_CONTEXT / getModelContextLimit(model);
}

function scaleUsage(usage, model) {
  if (!usage) return usage;
  const k = contextScale(model);
  if (k === 1) return usage;
  const out = { ...usage };
  if (typeof usage.input_tokens === 'number') out.input_tokens = Math.ceil(usage.input_tokens * k);
  if (typeof usage.output_tokens === 'number')
    out.output_tokens = Math.ceil(usage.output_tokens * k);
  return out;
}

// Rough char-based estimate of input tokens (used for the message_start event
// before the real count arrives in the final usage chunk). 4 chars/token is
// a common rule of thumb for English/dense code.
function estimateInputTokens(oaiReq) {
  try {
    return Math.ceil(JSON.stringify(oaiReq.messages).length / 4);
  } catch {
    return 0;
  }
}

function capMaxTokens(requested, model) {
  if (!requested || requested <= 0) return requested;
  const entry = findModel(stripProviderSuffix(model));
  let limit = SAFE_FALLBACK_OUTPUT;
  if (entry && entry.limit && typeof entry.limit.output === 'number') {
    limit = entry.limit.output;
  }
  return Math.min(requested, limit);
}

// OpenAI reasoning models (o1, o3, gpt-5) use max_completion_tokens (not
// max_tokens) and reject the temperature field. models.dev tags these with
// `reasoning: true`. When the catalog is unavailable we keep the old
// string-prefix heuristic so behavior degrades gracefully.
function needsMaxCompletionTokens(model) {
  if (!model) return false;
  const entry = findModel(stripProviderSuffix(model));
  if (entry) {
    return !!entry.reasoning;
  }
  // Fallback: string-prefix match, matching the pre-catalog behavior.
  const m = model.toLowerCase();
  return (
    m.startsWith('o1') ||
    m.startsWith('o3') ||
    m.startsWith('gpt-5') ||
    m.startsWith('gpt5') ||
    m.includes('codex')
  );
}

module.exports = {
  ANTHROPIC_CONTEXT,
  SAFE_FALLBACK_CONTEXT,
  SAFE_FALLBACK_OUTPUT,
  getModelContextLimit,
  contextScale,
  scaleUsage,
  estimateInputTokens,
  capMaxTokens,
  needsMaxCompletionTokens,
};
});

__ccproxy_register("nim", (require, exports, module) => {
// ---------- NVIDIA NIM detection via the model's -[Provider] suffix ----------
//
// cc-proxy is often pointed at an *aggregator* (one base URL) that bundles many
// underlying providers — one of which is NVIDIA NIM. The aggregator signals
// which sub-provider served a given model by tagging the model id with a
// `-[ProviderName]` suffix, e.g. `minimaxai/minimax-m3-[Nvidia]`. The upstream
// host is therefore a single fixed aggregator host, NOT `integrate.api.nvidia.com`,
// so host-based detection can't tell NIM traffic from any other provider's.
//
// The suffix is the only reliable NIM signal in that setup, so that's what we
// gate on. parseProviderSuffix(model) returns the bare provider name (lowercased)
// from the trailing `-[Name]`, or null. isNimModel(model) is true when that name
// is one of the NIM suffixes (default ["nvidia","nim"]; extensible via the
// CCPROXY_NIM_SUFFIXES env var).
//
// NIM rejects the top-level `enable_thinking` param and the `developer` message
// role, and expects per-family fields under `chat_template_kwargs` instead — see
// the family dispatch in src/thinking.js. applyThinking / request.js call
// isNimModel(model) per-request to decide that shaping. Note the suffix lives on
// the model id the aggregator receives, so it's available even though catalog
// lookups strip the suffix before resolving metadata.

const process = require('node:process');

// Match a trailing -[ProviderName] suffix (the form Claude Code's routing and
// aggregators append). Captures the inner name. Used only to read the suffix —
// stripping for catalog lookup is handled separately in catalog.js.
const SUFFIX_RE = /-\[([^\]]+)\]\s*$/;

// Provider-suffix names that mean "this request is served by NVIDIA NIM" and so
// must use the NIM param shaping. Lowercased. Extensible via the env var so a
// custom aggregator's tag name (e.g. -[nv-nim]) can be added without a code change.
const NIM_SUFFIXES = new Set([
  'nvidia',
  'nim',
  ...((typeof process !== 'undefined' && process.env && process.env.CCPROXY_NIM_SUFFIXES) || '')
    .split(',')
    .map((s) => s.trim().toLowerCase())
    .filter(Boolean),
]);

// Read the -[Provider] suffix off a model id. Returns the inner name lowercased,
// or null when there is no suffix. Returns null rather than throwing on bad input.
function parseProviderSuffix(model) {
  if (!model || typeof model !== 'string') return null;
  const m = model.match(SUFFIX_RE);
  return m ? m[1].trim().toLowerCase() : null;
}

// The NIM gate. True when the model's -[Provider] suffix names a NIM provider.
function isNimModel(model) {
  const s = parseProviderSuffix(model);
  return s !== null && NIM_SUFFIXES.has(s);
}

module.exports = {
  isNimModel,
  parseProviderSuffix,
  NIM_SUFFIXES,
};
});

__ccproxy_register("thinking", (require, exports, module) => {
// Map Anthropic's extended thinking to the upstream's reasoning field.
// Driven by the models.dev `reasoning_options` for each model.
//
// reasoning_options shapes we handle (non-NIM upstreams):
//   * {type:'effort', values:['low','medium','high',...]} — pick a value
//     from the model's own allowed list using a budget-tokens ladder.
//   * {type:'toggle'} — flip enable_thinking: true (qwen, deepseek-r1).
//   * {type:'budget_tokens', min, max} — emit thinking_budget: number
//     (clamped to [min, max]). Used by gemini-2.5.
//
// NVIDIA NIM is a special case: it rejects the top-level `enable_thinking`
// param and the `developer` message role, and expects per-family fields
// nested in `chat_template_kwargs` instead. cc-proxy often sits in front of an
// aggregator that bundles many providers; the aggregator tags a request as
// NIM-served by appending a -[Provider] suffix to the model id (e.g.
// `minimaxai/minimax-m3-[Nvidia]`). isNimModel(model) keys off THAT suffix,
// not the upstream host (the host is the fixed aggregator URL, useless as a
// signal) nor the catalog-resolved provider name (a metadata heuristic that
// resolves `moonshotai/kimi-k2.6-[Nvidia]` to the `moonshotai` catalog entry,
// not `nvidia`). When isNimModel() is true we dispatch on entry.family to emit
// the NIM-specific shape; non-NIM models keep the cascade below. If the model
// carries a NIM suffix but isn't in the catalog, thinking is silently dropped
// rather than emitting a param NIM would reject — we never 400.
//
// If the model isn't in the catalog and no recognizable family pattern
// applies, drop `thinking` silently.

const { findModel, stripProviderSuffix } = require('./catalog.js');
const { isNimModel } = require('./nim.js');

const REASONING_BUDGET_LADDER = [2000, 8000, 24000, 80000];

// Pick a value from `values` for a given `budget`. Walks the ladder from
// highest to lowest and maps the matched rung to the closest index in the
// model's own values array. Falls back to the lowest value if budget is
// below all thresholds.
function pickEffort(values, budget) {
  if (!Array.isArray(values) || values.length === 0) return undefined;
  // Find the highest ladder rung the budget clears.
  let rung = 0;
  for (let i = 0; i < REASONING_BUDGET_LADDER.length; i++) {
    if (budget >= REASONING_BUDGET_LADDER[i]) rung = i;
  }
  // Map the rung onto the values array. With equal lengths, rung-to-value
  // is 1:1. Otherwise we distribute evenly: values[idx] where idx is
  // rung * (len-1) / (ladderLen-1), clamped.
  if (values.length === REASONING_BUDGET_LADDER.length) return values[rung];
  const idx = Math.min(
    values.length - 1,
    Math.round((rung * (values.length - 1)) / (REASONING_BUDGET_LADDER.length - 1)),
  );
  return values[idx];
}

// Find the first {type:'effort'} option in the entry's reasoning_options and
// resolve a value for the budget. Returns undefined if the entry has no
// effort option or no allowed values.
function resolveEffort(entry, budget) {
  if (!entry || !Array.isArray(entry.reasoning_options)) return undefined;
  const effort = entry.reasoning_options.find((o) => o && o.type === 'effort');
  if (!effort || !Array.isArray(effort.values) || !effort.values.length) return undefined;
  return pickEffort(effort.values, budget);
}

// applyThinking dispatches between the NIM path and the standard path. Both
// share the same entry lookup so the catalog is consulted once.
function applyThinking(anth, req, model) {
  const t = anth.thinking;
  const enabled = t && t.type && t.type !== 'disabled';
  const entry = findModel(stripProviderSuffix(model));

  if (isNimModel(model)) {
    applyNimThinking(req, entry, t, enabled);
    return;
  }

  applyStandardThinking(req, entry, t, enabled);
}

// ---- NVIDIA NIM ----
//
// NIM rejects the top-level `enable_thinking` param; it wants a
// family-specific field nested inside `chat_template_kwargs`. We dispatch on
// entry.family:
//
//   minimax*           → {thinking_mode: 'enabled'|'disabled'}
//   kimi*              → {thinking: true}  (+ reasoning_effort if effort opt)
//   glm*               → {enable_thinking: true, clear_thinking: false}
//   deepseek*          → {thinking: true}  (+ reasoning_effort if effort opt)
//   nemotron / other   → {thinking: true}     (nvidia in-house default)
//
// "Off" (thinking disabled/absent): minimax asks for {thinking_mode:'disabled'}
// explicitly; every other family just omits chat_template_kwargs so the model
// defaults to no thinking (the conservative, cross-family-safe choice).
//
// When the resolved entry also carries a {type:'effort'} reasoning_option
// (kimi-k2.6 and deepseek-v4 on the nvidia catalog do), NIM accepts the
// standard `reasoning_effort` top-level field, so we emit BOTH the kwargs
// toggle and reasoning_effort. (When the entry resolves via a provider whose
// copy is toggle-only — e.g. `moonshotai/kimi-k2.6` lands on the moonshotai
// catalog provider's toggle copy — there's no effort list, so reasoning_effort
// is simply omitted and we send the kwargs alone.)
function applyNimThinking(req, entry, t, enabled) {
  const family = (entry && entry.family) || '';

  if (!enabled || !entry) {
    // Minimax needs an explicit disabled; others omit kwargs entirely.
    if (enabled === false && family.startsWith('minimax')) {
      req.chat_template_kwargs = { thinking_mode: 'disabled' };
    }
    return;
  }

  const budget = (t && t.budget_tokens) || 0;
  if (family.startsWith('minimax')) {
    req.chat_template_kwargs = { thinking_mode: 'enabled' };
  } else if (family.startsWith('kimi')) {
    req.chat_template_kwargs = { thinking: true };
  } else if (family.startsWith('glm')) {
    req.chat_template_kwargs = { enable_thinking: true, clear_thinking: false };
  } else if (family.startsWith('deepseek')) {
    req.chat_template_kwargs = { thinking: true };
  } else {
    // nemotron and other nvidia in-house families: {thinking: true}.
    req.chat_template_kwargs = { thinking: true };
  }

  // kimi and deepseek are the two NIM families the nvidia catalog tags with a
  // {type:'effort'} option; for those, NIM accepts the standard top-level
  // reasoning_effort alongside the chat_template_kwargs toggle. glm/minimax/
  // nemotron take a fixed enable field with no effort level, so we must NOT
  // add reasoning_effort (their NIM shape is the kwargs alone — emitting an
  // effort value sourced from a non-nvidia catalog copy would risk a 400).
  if (family.startsWith('kimi') || family.startsWith('deepseek')) {
    const effort = resolveEffort(entry, budget);
    if (effort) req.reasoning_effort = effort;
  }
}

// ---- Standard (non-NIM) path ----
//
// Preserved unchanged from the original applyThinking: effort → budget_tokens
// → toggle cascade. OpenRouter, Anthropic, OpenAI, each vendor's own platform
// API, Groq, etc. all take this path.
function applyStandardThinking(req, entry, t, enabled) {
  if (!enabled) {
    // On a known reasoning model, explicitly turn reasoning off so the
    // upstream doesn't burn budget when the client asked for none.
    if (entry && entry.reasoning) req.reasoning_effort = 'none';
    return;
  }

  const budget = t.budget_tokens || 0;
  const opts = entry && Array.isArray(entry.reasoning_options) ? entry.reasoning_options : [];

  // effort-style
  const effort = opts.find((o) => o && o.type === 'effort');
  if (effort && Array.isArray(effort.values) && effort.values.length) {
    req.reasoning_effort = pickEffort(effort.values, budget);
    return;
  }

  // budget_tokens-style (gemini-2.5): emit integer thinking_budget clamped
  // to the model's [min, max] window. If no budget was supplied, default
  // to the midpoint of the range.
  const budgetOpt = opts.find((o) => o && o.type === 'budget_tokens');
  if (budgetOpt) {
    const min = typeof budgetOpt.min === 'number' ? budgetOpt.min : 0;
    const max = typeof budgetOpt.max === 'number' ? budgetOpt.max : 24576;
    const v = budget || Math.round((min + max) / 2) || min || max;
    req.thinking_budget = Math.max(min, Math.min(max, v));
    return;
  }

  // toggle-style
  const toggle = opts.find((o) => o && o.type === 'toggle');
  if (toggle) {
    req.enable_thinking = true;
    if (budget) req.thinking_budget = budget;
    return;
  }
}

module.exports = { applyThinking, pickEffort };
});

__ccproxy_register("images", (require, exports, module) => {
// resolveImageSource turns an Anthropic image block into an OpenAI image_url
// part. Forward-compatible 2nd arg opts { imageFetch, maxImageBytes } lets
// the server pass its config in; the old single-arg form still works (uses
// the legacy module-level IMAGE_FETCH / MAX_IMAGE_BYTES globals as defaults).
//
// The legacy globals are read lazily via the exported setters so the server
// module can override them at boot — keeping the public signature stable.

let IMAGE_FETCH = false;
let MAX_IMAGE_BYTES = 20 * 1024 * 1024;

function configureImages({ imageFetch, maxImageBytes } = {}) {
  if (imageFetch !== undefined) IMAGE_FETCH = !!imageFetch;
  if (maxImageBytes !== undefined) MAX_IMAGE_BYTES = parseInt(maxImageBytes, 10);
}

async function resolveImageSource(source, opts = {}) {
  const imageFetch = opts.imageFetch !== undefined ? opts.imageFetch : IMAGE_FETCH;
  const maxImageBytes = opts.maxImageBytes !== undefined ? opts.maxImageBytes : MAX_IMAGE_BYTES;
  if (!source) throw new Error('image: missing source');
  if (source.type === 'base64') {
    if (!source.media_type || !source.data)
      throw new Error('image: base64 source missing media_type or data');
    return {
      type: 'image_url',
      image_url: { url: `data:${source.media_type};base64,${source.data}` },
    };
  }
  if (source.type === 'url') {
    if (!source.url) throw new Error('image: url source missing url');
    if (!imageFetch) return { type: 'image_url', image_url: { url: source.url } };
    // Server-side fetch + base64 re-encode. Use when the upstream doesn't
    // accept URL image inputs (Ollama, llama.cpp, vLLM with file refs, etc.).
    const r = await fetch(source.url, { signal: AbortSignal.timeout(10000) });
    if (!r.ok) throw new Error(`image: fetch ${source.url} returned ${r.status}`);
    const buf = Buffer.from(await r.arrayBuffer());
    if (buf.length > maxImageBytes) {
      throw new Error(
        `image: ${buf.length} bytes from ${source.url} exceeds --max-image-bytes (${maxImageBytes})`,
      );
    }
    const ct = r.headers.get('content-type') || 'image/png';
    return { type: 'image_url', image_url: { url: `data:${ct};base64,${buf.toString('base64')}` } };
  }
  if (source.type === 'file') {
    throw new Error('image: file source type (Anthropic Files API) is not supported by this proxy');
  }
  throw new Error(`image: unknown source type: ${source.type}`);
}

module.exports = { resolveImageSource, configureImages };
});

__ccproxy_register("request", (require, exports, module) => {
// ---------- Anthropic request -> OpenAI request ----------

const process = require('node:process');

const { needsMaxCompletionTokens, capMaxTokens } = require('./models.js');
const { cleanupSchemaForChatCompletions } = require('./schema.js');
const { applyThinking } = require('./thinking.js');
const { resolveImageSource } = require('./images.js');
const { modelSupportsVision } = require('./catalog.js');
const { isNimModel } = require('./nim.js');

// Module-level config that buildOpenAIRequest's single-arg form reads.
// Forward-compatible 2nd arg opts { modelOverride } overrides it; the server
// module calls configureRequest({ modelOverride }) at boot to set the —model
// override.
let MODEL_OVERRIDE = '';

function configureRequest({ modelOverride } = {}) {
  if (modelOverride !== undefined) MODEL_OVERRIDE = modelOverride;
}

async function anthropicToOpenAIMessages(anth, model) {
  const out = [];
  if (anth.system) {
    const sys =
      typeof anth.system === 'string'
        ? anth.system
        : (anth.system || []).map((b) => b.text || '').join('\n\n');
    if (sys)
      out.push({
        role: needsMaxCompletionTokens(model) && !isNimModel(model) ? 'developer' : 'system',
        content: sys,
      });
  }
  for (const m of anth.messages || []) {
    if (typeof m.content === 'string') {
      out.push({ role: m.role, content: m.content });
      continue;
    }
    const textParts = [];
    const toolCalls = [];
    const toolResults = [];
    const trailingImages = []; // images that can't fit in a tool message; appended as user messages
    for (const b of m.content || []) {
      if (b.type === 'text') {
        textParts.push(b.text);
      } else if (b.type === 'image' && b.source) {
        if (modelSupportsVision(model)) {
          textParts.push(await resolveImageSource(b.source));
        } else if (process.env.LOG) {
          console.log(`  ~ dropping image (model ${model} does not support vision)`);
        }
      } else if (b.type === 'tool_use') {
        toolCalls.push({
          id: b.id,
          type: 'function',
          function: { name: b.name, arguments: JSON.stringify(b.input ?? {}) },
        });
      } else if (b.type === 'tool_result') {
        // Anthropic tool_result.content can be a string or an array of
        // text+image blocks. OpenAI tool messages are text-only, so images
        // get appended as a follow-up user message (with a short caption).
        let text = '';
        if (typeof b.content === 'string') {
          text = b.content;
        } else if (Array.isArray(b.content)) {
          const textBits = [];
          for (const x of b.content) {
            if (!x) continue;
            if (x.type === 'text') textBits.push(x.text || '');
            else if (x.type === 'image' && x.source) {
              if (modelSupportsVision(model)) {
                const img = await resolveImageSource(x.source);
                trailingImages.push({ ...img, _caption: textBits.join('\n') || null });
                textBits.length = 0; // image content is moved out
              } else if (process.env.LOG) {
                console.log(`  ~ dropping image (model ${model} does not support vision)`);
              }
            }
          }
          text = textBits.join('\n');
        }
        toolResults.push({
          role: 'tool',
          tool_call_id: b.tool_use_id,
          content: b.is_error ? `[tool error] ${text}` : text,
        });
      }
      // 'thinking' / 'redacted_thinking' blocks: dropped.
    }
    if (m.role === 'assistant') {
      const msg = { role: 'assistant', content: textParts.length ? textParts.join('') : null };
      if (toolCalls.length) msg.tool_calls = toolCalls;
      out.push(msg);
    } else if (m.role === 'user') {
      if (textParts.length) {
        // If anything is non-string (image), emit the array form with all parts
        // as typed objects. Otherwise join to a single string.
        const hasNonString = textParts.some((p) => typeof p !== 'string');
        if (hasNonString) {
          const content = textParts.map((p) =>
            typeof p === 'string' ? { type: 'text', text: p } : p,
          );
          out.push({ role: 'user', content });
        } else {
          out.push({ role: 'user', content: textParts.join('') });
        }
      }
      for (const tr of toolResults) out.push(tr);
      for (const img of trailingImages) {
        const parts = [];
        if (img._caption)
          parts.push({ type: 'text', text: `[tool returned an image] ${img._caption}` });
        else parts.push({ type: 'text', text: '[tool returned an image]' });
        parts.push({ type: 'image_url', image_url: img.image_url });
        out.push({ role: 'user', content: parts });
      }
    }
  }
  return out;
}

function anthropicToOpenAITools(tools) {
  if (!tools) return undefined;
  return tools.map((t) => {
    const fn = {
      name: t.name,
      description: t.description,
      parameters: t.input_schema ? cleanupSchemaForChatCompletions(t.input_schema) : t.input_schema,
    };
    return {
      type: 'function',
      function: fn,
      // strict: false is critical — Anthropic marks every param as required,
      // so OpenAI's strict validation rejects the call when an optional is omitted.
    };
  });
}

function mapToolChoice(tc) {
  if (!tc) return undefined;
  if (tc.type === 'auto') return 'auto';
  if (tc.type === 'any') return 'required';
  if (tc.type === 'none') return 'none';
  if (tc.type === 'tool' && tc.name) return { type: 'function', function: { name: tc.name } };
  return undefined;
}

async function buildOpenAIRequest(anth, opts = {}) {
  const modelOverride = opts.modelOverride !== undefined ? opts.modelOverride : MODEL_OVERRIDE;
  const model = modelOverride || anth.model;
  const req = {
    model,
    messages: await anthropicToOpenAIMessages(anth, model),
    stream: !!anth.stream,
  };
  const maxTok = capMaxTokens(anth.max_tokens, model);
  // For o-series and gpt-5 we use max_completion_tokens instead of max_tokens.
  if (needsMaxCompletionTokens(model) && maxTok > 0) req.max_completion_tokens = maxTok;
  else if (maxTok > 0) req.max_tokens = maxTok;
  if (anth.temperature !== undefined && !needsMaxCompletionTokens(model)) {
    req.temperature = anth.temperature;
  }
  if (anth.top_p !== undefined) req.top_p = anth.top_p;
  if (anth.stop_sequences) req.stop = anth.stop_sequences;
  const tools = anthropicToOpenAITools(anth.tools);
  if (tools) req.tools = tools;
  const tc = mapToolChoice(anth.tool_choice);
  if (tc) req.tool_choice = tc;
  if (anth.stream) req.stream_options = { include_usage: true };
  applyThinking(anth, req, model);
  return req;
}

module.exports = {
  anthropicToOpenAIMessages,
  anthropicToOpenAITools,
  mapToolChoice,
  buildOpenAIRequest,
  configureRequest,
};
});

__ccproxy_register("stream", (require, exports, module) => {
// ---------- OpenAI stream -> Anthropic SSE ----------

const { msgId, sse } = require('./ids.js');
const { scaleUsage } = require('./models.js');

class StreamBuilder {
  constructor(model) {
    this.model = model;
    this.messageId = msgId();
    this.blockIndex = 0;
    this.textBlockOpen = false;
    this.textBlockIndex = -1;
    this.thinkingBlockOpen = false;
    this.thinkingBlockIndex = -1;
    this.toolBlocks = new Map(); // tool_call_id -> {index, name, args}
    this.toolIndexMap = new Map(); // oai delta index -> tool_call_id
    this.inputTokens = 0;
    this.outputTokens = 0;
    this.finishReason = 'end_turn';
  }

  start(estimatedInputTokens) {
    const usage = scaleUsage(
      { input_tokens: estimatedInputTokens || 0, output_tokens: 0 },
      this.model,
    );
    return sse('message_start', {
      type: 'message_start',
      message: {
        id: this.messageId,
        type: 'message',
        role: 'assistant',
        content: [],
        model: this.model,
        stop_reason: null,
        stop_sequence: null,
        usage,
      },
    });
  }

  // Returns the SSE chunk + true if it opened a new block; false if the
  // thinking block is already open or if `text` was empty.
  openThinking(text) {
    if (!text) return '';
    let out = '';
    if (!this.thinkingBlockOpen) {
      this.thinkingBlockIndex = this.blockIndex++;
      this.thinkingBlockOpen = true;
      out += sse('content_block_start', {
        type: 'content_block_start',
        index: this.thinkingBlockIndex,
        content_block: { type: 'thinking', thinking: '' },
      });
    }
    out += sse('content_block_delta', {
      type: 'content_block_delta',
      index: this.thinkingBlockIndex,
      delta: { type: 'thinking_delta', thinking: text },
    });
    return out;
  }

  closeThinking() {
    if (!this.thinkingBlockOpen) return '';
    this.thinkingBlockOpen = false;
    const out = sse('content_block_stop', {
      type: 'content_block_stop',
      index: this.thinkingBlockIndex,
    });
    this.thinkingBlockIndex = -1;
    return out;
  }

  openText() {
    if (this.textBlockOpen) return '';
    // If a thinking block is still open when text starts, close it first
    // (mirrors what ollama's anthropic adapter does at line ~821).
    const prefix = this.closeThinking();
    this.textBlockOpen = true;
    this.textBlockIndex = this.blockIndex++;
    return (
      prefix +
      sse('content_block_start', {
        type: 'content_block_start',
        index: this.textBlockIndex,
        content_block: { type: 'text', text: '' },
      })
    );
  }

  closeText() {
    if (!this.textBlockOpen) return '';
    this.textBlockOpen = false;
    const out = sse('content_block_stop', {
      type: 'content_block_stop',
      index: this.textBlockIndex,
    });
    this.textBlockIndex = -1;
    return out;
  }

  text(t) {
    if (!t) return '';
    const prefix = this.textBlockOpen ? '' : this.openText();
    return (
      prefix +
      sse('content_block_delta', {
        type: 'content_block_delta',
        index: this.textBlockIndex,
        delta: { type: 'text_delta', text: t },
      })
    );
  }

  openToolCall(oaiIndex, id, name) {
    let out = '';
    if (this.textBlockOpen) out += this.closeText();
    out += this.closeThinking();
    const idx = this.blockIndex++;
    this.toolBlocks.set(id, { index: idx, name, args: '' });
    this.toolIndexMap.set(oaiIndex, id);
    out += sse('content_block_start', {
      type: 'content_block_start',
      index: idx,
      content_block: { type: 'tool_use', id, name, input: {} },
    });
    return out;
  }

  appendToolArgs(oaiIndex, partialArgs) {
    const id = this.toolIndexMap.get(oaiIndex);
    if (!id) return '';
    const info = this.toolBlocks.get(id);
    if (!info) return '';
    info.args += partialArgs;
    return sse('content_block_delta', {
      type: 'content_block_delta',
      index: info.index,
      delta: { type: 'input_json_delta', partial_json: partialArgs },
    });
  }

  closeAllToolBlocks() {
    let out = '';
    for (const info of this.toolBlocks.values()) {
      out += sse('content_block_stop', { type: 'content_block_stop', index: info.index });
    }
    this.toolBlocks.clear();
    this.toolIndexMap.clear();
    return out;
  }

  finish(usage) {
    let out = '';
    if (this.textBlockOpen) out += this.closeText();
    out += this.closeThinking();
    out += this.closeAllToolBlocks();
    const upstreamOutput = usage?.completion_tokens ?? this.outputTokens;
    const scaled = scaleUsage(
      {
        output_tokens: upstreamOutput,
        reasoning_tokens: usage?.output_tokens_details?.reasoning_tokens || 0,
      },
      this.model,
    );
    out += sse('message_delta', {
      type: 'message_delta',
      delta: { stop_reason: this.finishReason, stop_sequence: null },
      usage: scaled,
    });
    out += sse('message_stop', { type: 'message_stop' });
    return out;
  }
}

function parseSSEEvents(buf) {
  const events = [];
  let start = 0;
  const sep = /\r?\n\r?\n/g;
  sep.lastIndex = 0;
  let m;
  while ((m = sep.exec(buf)) !== null) {
    const block = buf.slice(start, m.index);
    start = m.index + m[0].length;
    let data = '';
    for (const line of block.split(/\r?\n/)) {
      if (line.startsWith('data:')) data += line.slice(5).trim();
    }
    if (!data || data === '[DONE]') continue;
    try {
      events.push(JSON.parse(data));
    } catch {
      /* skip malformed */
    }
  }
  return { events, rest: buf.slice(start) };
}

function mapFinishReason(reason) {
  if (reason === 'tool_calls' || reason === 'function_call') return 'tool_use';
  if (reason === 'length' || reason === 'max_tokens') return 'max_tokens';
  if (reason === 'content_filter' || reason === 'safety') return 'end_turn';
  return 'end_turn';
}

module.exports = { StreamBuilder, parseSSEEvents, mapFinishReason };
});

__ccproxy_register("cli", (require, exports, module) => {
// ---------- config / CLI ----------

const { version } = require('../package.json');

function parseArgs(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--base' || a === '-b') out.base = argv[++i];
    else if (a === '--key' || a === '-k') out.key = argv[++i];
    else if (a === '--port' || a === '-p') out.port = argv[++i];
    else if (a === '--model' || a === '-m') out.model = argv[++i];
    else if (a === '--image-fetch') out.imageFetch = true;
    else if (a === '--max-image-bytes') out.maxImageBytes = argv[++i];
    else if (a === '--version' || a === '-v') {
      process.stdout.write(`cc-proxy/${version} node/${process.versions.node}\n`);
      process.exit(0);
    } else if (a === '--help' || a === '-h') {
      printHelp();
      process.exit(0);
    }
  }
  return out;
}

function printHelp() {
  process.stdout.write(`Usage: cc-proxy [options]\n\nOptions:\n  -b, --base <url>           OpenAI-compatible base URL (e.g. http://localhost:11434/v1)\n  -k, --key <key>            API key sent as Bearer to upstream\n  -p, --port <port>          Port to listen on (default 8082); bumped automatically if in use\n  -m, --model <name>         Override the model name in every request\n      --image-fetch          Fetch+base64 re-encode image URL sources server-side\n                             (use when upstream doesn't accept URL image inputs)\n      --max-image-bytes <n>  Max bytes per image when --image-fetch is on (default 20M)\n  -v, --version              Print version and exit\n  -h, --help                 Show this help\n\nWhen -b and -k are both omitted in a terminal, cc-proxy walks you through\ncreating or selecting a saved profile (~/.config/cc-proxy/profiles.json)\nwith arrow-key navigation.\n\nEnv vars: OPENAI_BASE_URL, OPENAI_API_KEY, PORT, MODEL_OVERRIDE,\n          IMAGE_FETCH=1, MAX_IMAGE_BYTES, LOG=1\n`);
}

module.exports = { parseArgs, printHelp, version };
});

__ccproxy_register("profiles", (require, exports, module) => {
// ---------- saved upstream profiles (interactive when -b/-k omitted) ----------
//
// Profiles live at ~/.config/cc-proxy/profiles.json so the same set is
// available regardless of cwd. Keys are stored in plain text on purpose:
// this is a local CLI convenience, not a secrets manager. Pass -b/-k (or
// set env vars in non-TTY) if you do not want credentials on disk.

const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const readline = require('node:readline');

const DEFAULT_BASE = 'http://localhost:11434/v1';
const CONFIG_DIR = path.join(os.homedir(), '.config', 'cc-proxy');
const PROFILES_FILE = path.join(CONFIG_DIR, 'profiles.json');
// Pre-migration location (v1); still read once if the new path is empty.
const LEGACY_PROFILES_FILE = path.join(os.homedir(), '.cc-proxy', 'profiles.json');

const CREATE_LABEL = 'Create new profile';

function defaultStore() {
  return { profiles: {}, lastUsed: null };
}

function parseStoreJson(raw) {
  const j = JSON.parse(raw);
  if (!j || typeof j !== 'object') return defaultStore();
  const profiles = j.profiles && typeof j.profiles === 'object' ? j.profiles : {};
  const cleaned = {};
  for (const [name, p] of Object.entries(profiles)) {
    if (!p || typeof p !== 'object') continue;
    if (typeof p.base !== 'string' || !p.base.trim()) continue;
    cleaned[name] = {
      base: String(p.base).replace(/\/$/, ''),
      key: typeof p.key === 'string' ? p.key : '',
    };
  }
  const lastUsed = typeof j.lastUsed === 'string' && cleaned[j.lastUsed] ? j.lastUsed : null;
  return { profiles: cleaned, lastUsed };
}

function loadStore(filePath = PROFILES_FILE) {
  try {
    const raw = fs.readFileSync(filePath, 'utf8');
    return parseStoreJson(raw);
  } catch {
    // fall through
  }

  // One-time migrate from ~/.cc-proxy/profiles.json when loading the
  // default path and the new file is missing.
  if (filePath === PROFILES_FILE) {
    try {
      const raw = fs.readFileSync(LEGACY_PROFILES_FILE, 'utf8');
      const store = parseStoreJson(raw);
      if (Object.keys(store.profiles).length > 0) {
        saveStore(store, PROFILES_FILE);
        process.stdout.write(
          `[profiles] migrated ${Object.keys(store.profiles).length} profile(s) to ~/.config/cc-proxy/\n`,
        );
        return store;
      }
    } catch {
      // no legacy file
    }
  }

  return defaultStore();
}

function saveStore(store, filePath = PROFILES_FILE) {
  const dir = path.dirname(filePath);
  fs.mkdirSync(dir, { recursive: true });
  const tmp = filePath + '.tmp';
  const payload = {
    profiles: store.profiles,
    lastUsed: store.lastUsed,
  };
  fs.writeFileSync(tmp, JSON.stringify(payload, null, 2) + '\n', { mode: 0o600 });
  fs.renameSync(tmp, filePath);
  try {
    fs.chmodSync(filePath, 0o600);
  } catch {
    // Windows may ignore mode; best-effort.
  }
}

function listProfileNames(store) {
  return Object.keys(store.profiles).sort((a, b) => a.localeCompare(b));
}

function isInteractive() {
  return !!(process.stdin.isTTY && process.stdout.isTTY);
}

function createRl() {
  return readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
}

function question(rl, prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, (answer) => resolve(answer));
  });
}

function sanitizeName(raw) {
  return String(raw || '')
    .trim()
    .replace(/[\\/]/g, '-')
    .replace(/\s+/g, '-');
}

function profileMenuItems(names, store) {
  const items = names.map((name) => {
    const p = store.profiles[name];
    const mark = name === store.lastUsed ? ' (last used)' : '';
    return `${name}  ${p.base}${mark}`;
  });
  items.push(CREATE_LABEL);
  return items;
}

/**
 * Arrow-key list picker. ↑/↓ move, Enter confirms, Ctrl+C aborts.
 * `items` is an array of display strings; returns the selected index.
 *
 * Inject `chooseIndex` in tests, or pass a custom `readKey` that yields
 * 'up' | 'down' | 'enter' | 'abort' for scripted selection.
 */
async function selectFromList(items, options = {}) {
  if (!items.length) throw new Error('selectFromList: empty items');

  if (typeof options.chooseIndex === 'function') {
    return options.chooseIndex(items, options.initialIndex || 0);
  }

  const stdin = options.stdin || process.stdin;
  const stdout = options.stdout || process.stdout;
  let index = Math.min(Math.max(options.initialIndex || 0, 0), items.length - 1);

  const hideCursor = '\x1b[?25l';
  const showCursor = '\x1b[?25h';
  const clearLine = '\x1b[2K';

  function draw(first) {
    if (!first) {
      // Move cursor to the top of the menu block we already printed.
      stdout.write(`\x1b[${items.length}A`);
    }
    for (let i = 0; i < items.length; i++) {
      const selected = i === index;
      const pointer = selected ? '❯ ' : '  ';
      const body = selected ? `\x1b[36m${pointer}${items[i]}\x1b[0m` : `${pointer}${items[i]}`;
      stdout.write(`\r${clearLine}${body}\n`);
    }
  }

  stdout.write('\nSelect a profile (↑/↓, Enter):\n');
  stdout.write(hideCursor);
  draw(true);

  const wasRaw = stdin.isRaw;
  if (typeof stdin.setRawMode === 'function') {
    stdin.setRawMode(true);
  }
  if (typeof stdin.resume === 'function') stdin.resume();

  try {
    for (;;) {
      const key = options.readKey ? await options.readKey() : await readArrowKey(stdin);

      if (key === 'abort') {
        stdout.write(showCursor);
        stdout.write('\n');
        process.exit(130);
      }
      if (key === 'up') {
        index = (index - 1 + items.length) % items.length;
        draw(false);
      } else if (key === 'down') {
        index = (index + 1) % items.length;
        draw(false);
      } else if (key === 'enter') {
        stdout.write(showCursor);
        return index;
      }
    }
  } finally {
    if (typeof stdin.setRawMode === 'function') {
      stdin.setRawMode(!!wasRaw);
    }
    stdout.write(showCursor);
  }
}

function readArrowKey(stdin) {
  return new Promise((resolve) => {
    let buf = Buffer.alloc(0);

    function onData(chunk) {
      buf = Buffer.concat([buf, Buffer.from(chunk)]);
      const s = buf.toString('utf8');

      // Ctrl+C
      if (s.includes('\u0003')) {
        cleanup();
        resolve('abort');
        return;
      }
      // Enter
      if (s.includes('\r') || s.includes('\n')) {
        cleanup();
        resolve('enter');
        return;
      }
      // ESC [ A/B  or  ESC O A/B  (application cursor keys)
      if (s.includes('\u001b[A') || s.includes('\u001bOA')) {
        cleanup();
        resolve('up');
        return;
      }
      if (s.includes('\u001b[B') || s.includes('\u001bOB')) {
        cleanup();
        resolve('down');
        return;
      }
      // Incomplete escape sequence — wait for more bytes.
      if (s === '\u001b' || s === '\u001b[' || s === '\u001bO') {
        return;
      }
      // Ignore other keys (including leftover noise); reset buffer.
      buf = Buffer.alloc(0);
    }

    function cleanup() {
      stdin.removeListener('data', onData);
    }

    stdin.on('data', onData);
  });
}

async function promptCreateProfile(rl, store, filePath = PROFILES_FILE) {
  process.stdout.write('\nCreate a new upstream profile.\n');
  process.stdout.write('(API keys are stored in plain text under ~/.config/cc-proxy/)\n\n');

  let name = '';
  while (!name) {
    const raw = await question(rl, 'Profile name: ');
    name = sanitizeName(raw);
    if (!name) {
      process.stdout.write('  Name is required.\n');
      continue;
    }
    if (store.profiles[name]) {
      const overwrite = await question(
        rl,
        `  Profile "${name}" already exists. Overwrite? [y/N]: `,
      );
      if (!/^\s*y(es)?\s*$/i.test(overwrite)) {
        name = '';
      }
    }
  }

  const baseRaw = await question(rl, `Base URL [${DEFAULT_BASE}]: `);
  const base = (baseRaw.trim() || DEFAULT_BASE).replace(/\/$/, '');
  const key = (await question(rl, 'API key (leave empty if none): ')).trim();

  store.profiles[name] = { base, key };
  store.lastUsed = name;
  saveStore(store, filePath);

  process.stdout.write(`\nSaved profile "${name}".\n`);
  return { name, base, key };
}

async function withRl(options, fn) {
  // Prefer an injected mock rl (tests). Otherwise open readline only for
  // the create-profile text prompts so it never steals keys during the
  // raw-mode arrow picker.
  if (options.rl) return fn(options.rl);

  const rl = createRl();
  try {
    return await fn(rl);
  } finally {
    rl.close();
  }
}

async function promptSelectProfile(store, filePath = PROFILES_FILE, selectOpts = {}) {
  const names = listProfileNames(store);
  if (names.length === 0) {
    return withRl(selectOpts, (rl) => promptCreateProfile(rl, store, filePath));
  }

  const items = profileMenuItems(names, store);
  const initialIndex =
    store.lastUsed && names.includes(store.lastUsed) ? names.indexOf(store.lastUsed) : 0;

  const picked = await selectFromList(items, {
    initialIndex,
    chooseIndex: selectOpts.chooseIndex,
    readKey: selectOpts.readKey,
    stdin: selectOpts.stdin,
    stdout: selectOpts.stdout,
  });

  // Last row is always "Create new profile".
  if (picked === names.length) {
    return withRl(selectOpts, (rl) => promptCreateProfile(rl, store, filePath));
  }

  const name = names[picked];
  const p = store.profiles[name];
  store.lastUsed = name;
  saveStore(store, filePath);
  process.stdout.write(`Using profile "${name}".\n`);
  return { name, base: p.base, key: p.key };
}

/**
 * Resolve base + key when the user did not pass -b / -k.
 * Interactive TTY: create or pick a saved profile.
 * Non-TTY: return null so the caller falls back to env/defaults.
 */
async function resolveFromProfiles(options = {}) {
  const filePath = options.filePath || PROFILES_FILE;
  const interactive = options.interactive != null ? options.interactive : isInteractive();

  if (!interactive) return null;

  const store = loadStore(filePath);
  return promptSelectProfile(store, filePath, {
    rl: options.rl,
    chooseIndex: options.chooseIndex,
    readKey: options.readKey,
    stdin: options.stdin,
    stdout: options.stdout,
  });
}

module.exports = {
  CONFIG_DIR,
  PROFILES_FILE,
  LEGACY_PROFILES_FILE,
  DEFAULT_BASE,
  CREATE_LABEL,
  loadStore,
  saveStore,
  listProfileNames,
  sanitizeName,
  isInteractive,
  selectFromList,
  resolveFromProfiles,
  promptCreateProfile,
  promptSelectProfile,
  profileMenuItems,
};
});

__ccproxy_register("server", (require, exports, module) => {
// ---------- HTTP server ----------

const http = require('http');
const process = require('node:process');

const { msgId, reqId } = require('./ids.js');
const { anthropicError, writeJsonError } = require('./errors.js');
const { fetchWithRetry, reqAbortSignal } = require('./retry.js');
const { buildOpenAIRequest, configureRequest } = require('./request.js');
const { configureImages } = require('./images.js');
const { estimateInputTokens, scaleUsage } = require('./models.js');
const { StreamBuilder, parseSSEEvents, mapFinishReason } = require('./stream.js');

// startServer(config) builds the http server but does NOT listen. The caller
// (src/main.js) calls .listen(port, banner). Returns the server instance.
function startServer(config) {
  const { base, key, modelOverride, imageFetch, maxImageBytes } = config;

  // Push config into the request + image modules so their single-arg paths
  // (used by buildOpenAIRequest, resolveImageSource) pick it up.
  configureRequest({ modelOverride });
  configureImages({ imageFetch, maxImageBytes });

  const BASE = base.replace(/\/$/, '');
  const KEY = key;
  const MODEL_OVERRIDE = modelOverride;

  const server = http.createServer(async (req, res) => {
    if (process.env.LOG) process.stdout.write(`> ${req.method} ${req.url}\n`);

    if (req.method === 'HEAD' && req.url === '/') {
      // Some clients (Claude Code) probe with HEAD before sending body.
      res.writeHead(200, { 'content-type': 'application/json' });
      res.end();
      return;
    }

    if (req.method === 'GET' && (req.url === '/' || req.url === '/health')) {
      res.writeHead(200, { 'content-type': 'application/json' });
      res.end(
        JSON.stringify({ status: 'ok', upstream: BASE, model_override: MODEL_OVERRIDE || null }),
      );
      return;
    }

    if (req.method === 'GET' && req.url === '/v1/models') {
      try {
        const r = await fetch(`${BASE}/models`, {
          headers: KEY ? { authorization: `Bearer ${KEY}` } : {},
        });
        const data = await r.json();
        if (!r.ok) {
          // Forward upstream failures as 502 in the Anthropic error envelope
          // so Claude Code surfaces them instead of silently seeing an empty
          // model list masked as success.
          if (res.writableEnded || res.destroyed) return;
          res.writeHead(502, { 'content-type': 'application/json' });
          res.end(
            JSON.stringify({
              type: 'error',
              error: anthropicError(502, `upstream /models returned ${r.status}`).error,
              request_id: reqId(),
            }),
          );
          return;
        }
        res.writeHead(200, { 'content-type': 'application/json' });
        res.end(JSON.stringify(data));
      } catch {
        if (res.writableEnded || res.destroyed) return;
        res.writeHead(502, { 'content-type': 'application/json' });
        res.end(
          JSON.stringify({
            type: 'error',
            error: anthropicError(502, 'upstream /models fetch failed').error,
            request_id: reqId(),
          }),
        );
      }
      return;
    }

    // Strip query string for path matching (e.g. Claude Code sends ?beta=true).
    const reqPath = (req.url || '').split('?')[0];

    if (req.method !== 'POST' || reqPath !== '/v1/messages') {
      writeJsonError(res, 404, `not found: ${req.method} ${req.url}`);
      return;
    }

    let raw = '';
    try {
      for await (const chunk of req) raw += chunk;
    } catch (e) {
      if (res.writableEnded || res.destroyed) return;
      return writeJsonError(res, 502, 'request aborted: ' + e.message);
    }

    let anth;
    try {
      anth = JSON.parse(raw);
    } catch (e) {
      return writeJsonError(res, 400, 'invalid JSON: ' + e.message);
    }

    if (!anth.model) return writeJsonError(res, 400, 'model is required');
    if (!anth.max_tokens || anth.max_tokens <= 0)
      return writeJsonError(res, 400, 'max_tokens is required and must be positive');
    if (!Array.isArray(anth.messages) || anth.messages.length === 0)
      return writeJsonError(res, 400, 'messages is required');

    let oaiReq;
    try {
      oaiReq = await buildOpenAIRequest(anth);
    } catch (e) {
      if (process.env.LOG) console.log('  <- build error:', e.message);
      if (res.writableEnded || res.destroyed) return;
      res.writeHead(400, { 'content-type': 'application/json' });
      res.end(
        JSON.stringify({
          type: 'error',
          error: anthropicError(400, e.message).error,
          request_id: reqId(),
        }),
      );
      return;
    }
    if (process.env.LOG) {
      const summary = {
        model: oaiReq.model,
        msgs: oaiReq.messages.length,
        tools: oaiReq.tools?.length || 0,
        stream: oaiReq.stream,
      };
      console.log('  -> upstream', JSON.stringify(summary));
    }

    let upstream;
    try {
      upstream = await fetchWithRetry(
        `${BASE}/chat/completions`,
        {
          method: 'POST',
          headers: {
            'content-type': 'application/json',
            ...(KEY ? { authorization: `Bearer ${KEY}` } : {}),
          },
          body: JSON.stringify(oaiReq),
        },
        reqAbortSignal(req),
      );
    } catch (e) {
      if (process.env.LOG) console.log('  <- upstream fetch failed:', e.message);
      if (res.writableEnded || res.destroyed) return;
      res.writeHead(502, { 'content-type': 'application/json' });
      res.end(
        JSON.stringify({
          type: 'error',
          error: anthropicError(502, `upstream fetch failed: ${e.message}`).error,
          request_id: reqId(),
        }),
      );
      return;
    }

    if (!upstream.ok) {
      const errText = await upstream.text();
      let parsed = null;
      try {
        parsed = JSON.parse(errText);
      } catch {}
      const msg = parsed?.error?.message || errText || `upstream returned ${upstream.status}`;
      if (process.env.LOG)
        console.log('  <- upstream error', upstream.status, errText.slice(0, 500));
      if (res.writableEnded || res.destroyed) return;
      res.writeHead(upstream.status, { 'content-type': 'application/json' });
      res.end(
        JSON.stringify({
          type: 'error',
          error: anthropicError(upstream.status, msg).error,
          request_id: reqId(),
        }),
      );
      return;
    }

    // Non-streaming response
    if (!oaiReq.stream) {
      const data = await upstream.json();
      const choice = data.choices?.[0] || {};
      const msg = choice.message || {};
      const content = [];
      // Reasoning comes before text in the response, matching the streaming
      // block order (ollama/anthropic.go:659-680 and CLASP/stream.go:206-212).
      const thinking = msg.reasoning_content ?? msg.reasoning;
      if (thinking) content.push({ type: 'thinking', thinking });
      if (msg.content) content.push({ type: 'text', text: msg.content });
      if (Array.isArray(msg.tool_calls)) {
        for (const tc of msg.tool_calls) {
          let input = {};
          try {
            input = JSON.parse(tc.function?.arguments || '{}');
          } catch {}
          content.push({ type: 'tool_use', id: tc.id, name: tc.function.name, input });
        }
      }
      res.writeHead(200, { 'content-type': 'application/json' });
      res.end(
        JSON.stringify({
          id: data.id || msgId(),
          type: 'message',
          role: 'assistant',
          content,
          model: data.model || anth.model,
          stop_reason: mapFinishReason(choice.finish_reason),
          stop_sequence: null,
          usage: scaleUsage(
            {
              input_tokens: data.usage?.prompt_tokens || 0,
              output_tokens: data.usage?.completion_tokens || 0,
              reasoning_tokens: data.usage?.output_tokens_details?.reasoning_tokens || 0,
            },
            anth.model,
          ),
        }),
      );
      return;
    }

    // Streaming response
    res.writeHead(200, {
      'content-type': 'text/event-stream',
      'cache-control': 'no-cache',
      connection: 'keep-alive',
      'x-accel-buffering': 'no',
    });

    const b = new StreamBuilder(anth.model);
    res.write(b.start(estimateInputTokens(oaiReq)));

    // SSE keepalive ping. Reasoning models can sit silent 30-60s before the
    // first content delta, which trips idle timeouts at intermediate proxies
    // and cloud front-doors. Emitting a ping right after message_start and
    // every 15s afterwards defeats this. CLASP does the same (stream.go:424).
    const writePing = () => {
      if (res.writableEnded || res.destroyed) return false;
      res.write(`event: ping\ndata: ${JSON.stringify({ type: 'ping' })}\n\n`);
      return true;
    };
    writePing();
    const pingTimer = setInterval(writePing, 15000);

    const reader = upstream.body.getReader();
    const decoder = new TextDecoder();
    let buf = '';
    let usage = null;

    try {
      while (true) {
        const { value, done } = await reader.read();
        if (done) break;
        buf += decoder.decode(value, { stream: true });
        const { events, rest } = parseSSEEvents(buf);
        buf = rest;
        for (const ev of events) {
          if (ev.usage) usage = ev.usage;
          const choice = ev.choices?.[0];
          if (!choice) continue;
          const delta = choice.delta || {};
          // Reasoning/thinking content. Some providers use `reasoning` (Azure
          // OpenAI, mirrors CLASP's stream.go delta.Reasoning), others use
          // `reasoning_content` (DeepSeek-R1, Qwen, some Ollama-compat shims).
          const thinking = delta.reasoning ?? delta.reasoning_content;
          if (thinking) {
            const out = b.openThinking(thinking);
            if (out) res.write(out);
          }
          if (delta.content) {
            const out = b.text(delta.content);
            if (out) res.write(out);
          }
          if (Array.isArray(delta.tool_calls)) {
            for (const tc of delta.tool_calls) {
              const oaiIndex = tc.index ?? 0;
              if (tc.id && tc.function?.name) {
                res.write(b.openToolCall(oaiIndex, tc.id, tc.function.name));
              }
              if (tc.function?.arguments) {
                res.write(b.appendToolArgs(oaiIndex, tc.function.arguments));
              }
            }
          }
          if (choice.finish_reason) {
            b.finishReason = mapFinishReason(choice.finish_reason);
          }
        }
      }
      res.write(b.finish(usage));
      res.end();
      if (process.env.LOG) console.log('  <- done');
    } catch (e) {
      console.error('stream error:', e);
      try {
        res.end();
      } catch {}
    } finally {
      clearInterval(pingTimer);
    }
  });

  // Catch raw socket-level errors (ECONNRESET, etc.) that never reach the
  // request handler. Without this, Node defaults to destroying the socket
  // silently, but the async request handler may still reject unhandled.
  server.on('clientError', (err, socket) => {
    if (process.env.LOG) console.error('clientError:', err.code || err.message);
    if (socket.writable && !socket.destroyed) {
      socket.end('HTTP/1.1 400 Bad Request\r\n\r\n');
    } else {
      socket.destroy(err);
    }
  });

  return server;
}

module.exports = { startServer };
});

__ccproxy_register("main", (require, exports, module) => {
// ---------- entry: parse argv + env, start server, listen ----------
//
// Side-effect module. The build script loads this last (after all deps), so
// `require('../lib/proxy.js')` boots the proxy the same way the old monolith
// did. Kept side-effect-only so this file has nothing else to export.

const process = require('node:process');

const { parseArgs } = require('./cli.js');
const { startServer } = require('./server.js');
const { loadCatalog } = require('./catalog.js');
const { resolveFromProfiles } = require('./profiles.js');

// Maximum number of ports to try before giving up when EADDRINUSE is hit.
const MAX_PORT_ATTEMPTS = 10;

async function boot(argv) {
  const args = parseArgs(argv);

  // When neither -b nor -k is on the command line, offer saved profiles
  // (interactive TTY). Non-TTY falls through to env/defaults as before.
  let profileBase;
  let profileKey;
  let profileName;
  if (args.base === undefined && args.key === undefined) {
    const picked = await resolveFromProfiles();
    if (picked) {
      profileBase = picked.base;
      profileKey = picked.key;
      profileName = picked.name;
    }
  }

  const BASE = (
    args.base ||
    profileBase ||
    process.env.OPENAI_BASE_URL ||
    'http://localhost:11434/v1'
  ).replace(/\/$/, '');
  const KEY =
    args.key !== undefined
      ? args.key
      : profileKey !== undefined
        ? profileKey
        : process.env.OPENAI_API_KEY || '';
  const PORT = parseInt(args.port || process.env.PORT || '8082', 10);
  const MODEL_OVERRIDE = args.model || process.env.MODEL_OVERRIDE || '';
  const IMAGE_FETCH = !!args.imageFetch || process.env.IMAGE_FETCH === '1';
  const MAX_IMAGE_BYTES = parseInt(
    args.maxImageBytes || process.env.MAX_IMAGE_BYTES || String(20 * 1024 * 1024),
    10,
  );

  // Load the model catalog before the server starts accepting requests.
  // On first-ever boot this blocks for a network round trip; on every
  // subsequent boot it returns instantly from disk and fires a background
  // refresh.
  await loadCatalog();

  const server = startServer({
    base: BASE,
    key: KEY,
    modelOverride: MODEL_OVERRIDE,
    imageFetch: IMAGE_FETCH,
    maxImageBytes: MAX_IMAGE_BYTES,
  });

  // Try listening on PORT; if it's taken, increment and retry up to
  // MAX_PORT_ATTEMPTS times before giving up. Emits a warning so the user
  // knows which port was actually bound.
  const boundPort = await listenWithFallback(server, PORT);

  console.log(`Anthropic <-> OpenAI proxy listening on http://localhost:${boundPort}`);
  if (profileName) console.log(`  profile:  ${profileName}`);
  console.log(`  upstream: ${BASE}`);
  console.log(`  auth:     ${KEY ? 'bearer ***' + KEY.slice(-4) : 'none'}`);
  if (MODEL_OVERRIDE) console.log(`  model:    ${MODEL_OVERRIDE} (override)`);
  console.log('');
  console.log('To use with Claude Code:');
  console.log('');
  console.log('  bash / zsh:');
  console.log(
    `    ANTHROPIC_BASE_URL=http://localhost:${boundPort} ANTHROPIC_AUTH_TOKEN=any-value claude`,
  );
  console.log('');
  console.log('  PowerShell:');
  console.log(
    `    $env:ANTHROPIC_BASE_URL="http://localhost:${boundPort}"; $env:ANTHROPIC_AUTH_TOKEN="any-value"; claude`,
  );
  console.log('');
  console.log('  cmd:');
  console.log(
    `    set ANTHROPIC_BASE_URL=http://localhost:${boundPort} && set ANTHROPIC_AUTH_TOKEN=any-value && claude`,
  );
  console.log('');

  // Graceful shutdown. On SIGTERM/SIGINT we stop accepting new connections and
  // let in-flight requests drain. Each handler removes itself so a second
  // signal falls through to Node's default (immediate exit) — matching
  // conventional Ctrl-C-twice-to-force behavior. A hard timeout (default
  // 10s, overridable via CCPROXY_SHUTDOWN_TIMEOUT_MS) prevents a stuck client
  // from hanging the process.
  let shuttingDown = false;
  function shutdown(signal) {
    if (shuttingDown) return;
    shuttingDown = true;
    process.stdout.write(`\ncc-proxy received ${signal}, shutting down...\n`);
    process.removeListener('SIGTERM', onTerm);
    process.removeListener('SIGINT', onInt);
    const forceAfter = Number(process.env.CCPROXY_SHUTDOWN_TIMEOUT_MS) || 10000;
    const timer = setTimeout(() => {
      process.stderr.write('cc-proxy: forcing exit after shutdown timeout\n');
      process.exit(1);
    }, forceAfter).unref();
    server.close(() => {
      clearTimeout(timer);
      process.exit(0);
    });
  }
  function onTerm() {
    shutdown('SIGTERM');
  }
  function onInt() {
    shutdown('SIGINT');
  }
  process.on('SIGTERM', onTerm);
  process.on('SIGINT', onInt);

  return server;
}

/**
 * Attempt to listen on `port`. If EADDRINUSE is thrown, increment and retry
 * up to MAX_PORT_ATTEMPTS times. Resolves with the port that was actually
 * bound. Rejects if every attempt fails or a non-EADDRINUSE error is thrown.
 *
 * @param {import('node:http').Server} server
 * @param {number} port  Desired starting port
 * @returns {Promise<number>}  Bound port
 */
function listenWithFallback(server, port) {
  return new Promise((resolve, reject) => {
    let attempt = 0;

    function tryListen(p) {
      server.once('error', onError);
      server.listen(p, onListening);

      function onListening() {
        server.removeListener('error', onError);
        resolve(p);
      }

      function onError(err) {
        server.removeListener('listening', onListening);
        if (err.code !== 'EADDRINUSE') {
          return reject(err);
        }
        attempt++;
        if (attempt >= MAX_PORT_ATTEMPTS) {
          return reject(
            new Error(
              `could not bind to any port in range ${port}–${p} (all in use)`,
            ),
          );
        }
        process.stderr.write(
          `cc-proxy: port ${p} is already in use, trying ${p + 1}...\n`,
        );
        tryListen(p + 1);
      }
    }

    tryListen(port);
  });
}

// Always boot on load. The original monolith ran parseArgs + server.listen at
// module top level, so `require('../lib/proxy.js')` from bin/cc-proxy.js started
// the proxy. Bundling must preserve that — main is the last module loaded, and
// we boot here unconditionally to keep the manual-install path identical.
boot(process.argv.slice(2)).catch((e) => {
  console.error('cc-proxy failed to start:', e.message);
  process.exit(1);
});

module.exports = { boot, listenWithFallback };
});

__ccproxy_load('main');
