'use strict';

// Hand-rolled zero-dependency concat bundler.
//
// Problem this solves: the project keeps its source as one module per domain
// under src/ but ships a single lib/proxy.js so the README's manual-install
// curl URL stays stable. If we used a real bundler we'd pull in a runtime or
// pay a dev dep; instead we wrap each src/*.js in a CommonJS-module factory
// and stitch them together with a tiny custom module loader (__ccproxy_load)
// that resolves `require('./foo.js')` lookups against an in-bundle map.
//
// Output is idempotent: no timestamps, no absolute paths, no source-map
// references. Re-running the build over unchanged src/ produces a
// byte-identical lib/proxy.js. That invariant is the safety net for the
// auto-generated file being tracked in git.

const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const srcDir = path.join(root, 'src');
const outFile = path.join(root, 'lib', 'proxy.js');

// Dependency order — leaves first. Each module only requires things listed
// earlier in this array. `main` is last because it boots the server on load.
const ORDER = [
  'catalog',
  'ids',
  'errors',
  'retry',
  'schema',
  'models',
  'nim',
  'thinking',
  'images',
  'request',
  'stream',
  'cli',
  'profiles',
  'server',
  'main',
];

// Read each src file, strip the leading 'use strict'; (we'll add our own at
// the top of the bundle), and return { name, bodyWithoutUseStrict }.
function loadSources() {
  const out = [];
  for (const name of ORDER) {
    const file = path.join(srcDir, `${name}.js`);
    const raw = fs.readFileSync(file, 'utf8');
    // Strip a single leading 'use strict'; line if present. The bundle
    // declares 'use strict' once at the top — duplicate directives would
    // still be valid ES but we keep the output clean.
    const stripped = raw.replace(/^(['"])use strict\1;\s*\n?/, '');
    out.push({ name, body: stripped });
  }
  return out;
}

// Header: shebang + file banner + bootstrap loader.
// The captured outer `require` is used as a fallback for built-in modules
// (http) so src/*.js `require('http')` resolves to Node's built-in.
const HEADER = `#!/usr/bin/env node
// Anthropic <-> OpenAI proxy for Claude Code.
//
// AUTO-GENERATED by scripts/build.js — do not edit by hand.
// Source lives in src/. Run \`npm run build\` to regenerate.
//
// Usage:
//   node proxy.js --base https://api.openai.com/v1 --key sk-xxx --port 8082
//   or via env: OPENAI_BASE_URL, OPENAI_API_KEY, PORT, MODEL_OVERRIDE
//
// Then in Claude Code:
//   export ANTHROPIC_BASE_URL=http://localhost:8082
//   export ANTHROPIC_AUTH_TOKEN=any
//   claude --bare                  # interactive
//   claude -p --bare "your prompt" # non-interactive
//
// Notes:
//   * Thinking blocks from Claude Code are dropped (no OpenAI analogue).
//     Disable extended thinking in Claude Code if you want clean runs.
//   * Streaming is translated chunk-by-chunk from OpenAI SSE to Anthropic SSE.
//   * Tool calls: streams are stitched via OpenAI's \`index\` field, so multi-tool
//     and partial-arg deltas work.

'use strict';

const __ccproxy_externalRequire = require;
const __ccproxy_modules = {};
const __ccproxy_load = (name) => {
  const m = __ccproxy_modules[name];
  if (m.loaded) return m.exports;
  m.loaded = true;
  m.factory.call(void 0, m._require, m.exports, m);
  return m.exports;
};

function __ccproxy_register(name, factory) {
  const m = { exports: {}, loaded: false, factory };
  // Require shim: './foo.js' -> __ccproxy_load('foo'); anything else falls
  // through to the captured outer require (handles 'http' and other built-ins).
  m._require = (id) => {
    if (typeof id === 'string' && id.startsWith('./')) {
      return __ccproxy_load(id.replace(/^\\.\\//, '').replace(/\\.js$/, ''));
    }
    return __ccproxy_externalRequire(id);
  };
  __ccproxy_modules[name] = m;
}
`;

function build() {
  const sources = loadSources();
  const parts = [HEADER];

  for (const { name, body } of sources) {
    parts.push(`__ccproxy_register(${JSON.stringify(name)}, (require, exports, module) => {
${body}});
`);
  }

  // Boot — matches the old monolith's module-load side effect.
  parts.push(`__ccproxy_load('main');
`);

  const output = parts.join('\n');
  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, output, 'utf8');
}

build();
